### ISSUE TITLE
SimpleTracker integration

### ISSUE THREAD

**Issue by pjanku** [TBU-AILab/ArkArena#10]
**Description**
Implement the simple tracker together with Kilobot detection and Kilobot's LED detection. The tracker should provide information about each specific Kilobot, like its position, LED state and rotation. Moreover, the kilobot object should also contain a history of the previous position.  Finally, basic "drawing" should be available like a part of the tracker.

**Subtasks**

- [x] Add subproject as a part of the main ArkArena project
- [ ] Prepare GUI elements to control the simple tracker features
- [ ] Implement detection process as a separate thread (keep in my threadsafe approach)
- [ ] Implement drawing of kilobots onto the displayed image.
