### ISSUE TITLE
Experiment recording

### ISSUE THREAD

**Issue by pjanku** [TBU-AILab/ArkArena#11]
**Description**
The application should provide a recording functionality - it should be able to store captured images together with predefined overlays displaying detected kilobots. Moreover, the output should also be recorded in some way in the data file (CSV probably) where all essential metrics will be stored with the corresponding timestamp. 

**Subtasks**

- [ ] Prepare GUI elements (new pane)
- [ ] Implement image output recording
- [ ] Implement data file recording
