### ISSUE TITLE
Python Editor

### ISSUE THREAD

**Issue by pjanku** [TBU-AILab/ArkArena#17]
**Description**
The currently used editor is simple QTextEditor with not completely configured highlighter. The Highlighter need to be improved, the basic code completion needs to be added, and several features need to be implemented. At first, the configuration of the whole editor is done in MainWindow class. A new class derived from QTextEditor should be created with all the necessary steps inside it.

**Subtask**

- [ ] Create a derived class and move the current configuration inside it
- [ ] Improve the highlighter configuration
- [ ] Implement basic code completion
- [ ] Solve the problem with tabs (tab should be replaced by four spaces)
- [ ] Add line numbers

**Comment by yash013** [comment]
hello there, 
i am new to open source. can you guide me further? I want to do this task.
