### ISSUE TITLE
Python integration

### ISSUE THREAD

**Issue by pjanku** [TBU-AILab/ArkArena#9]
**Description**
Python will be used as a scripting language. Therefore python needs to be embedded into ArkArena. There should be a way how to transfer information from C++ (tracker etc.) into Python script and in opposite directions how to control the C++ part (sending commands over OHC, etc.)

**Subtasks**

- [x] Create GUI and Icons
- [x] Integrate python intepreter
- [x] Create a separate thread to execute python scripts
- [x] Redirect std output from the python section into the main app
- [x] Implement basic interface between Python and C++

**Comment by pjanku** [comment]
The std redirecting is not done in this meaning. New functions in ArkArena module are created to print out some messages into ArkArena output log dock. I hope that it is enough for now.
